### ISSUE TITLE
how to run (ex. yarn start)

### ISSUE THREAD

**Issue by ghost** [1-EXON/GameWatcherBot#1]

**Comment by 1-EXON** [comment]
yarn start!
+ settings.json 수정해주셔야합니다

**Comment by sihyeokpark** [comment]
src/index.ts 실행주시면 됩니다

**Comment by ghost** [comment]
![gh_issue_1](https://user-images.githubusercontent.com/65204013/108612604-8fcf2600-742d-11eb-8224-2eeb5f759a3b.png)

**Comment by ghost** [comment]
@1-EXON

**Comment by ghost** [comment]
package.json의 "type": "module" 를 지우니까 되네요.
